import Providers from '@/app/[lang]/_providers';
//ui
import { Header } from '@/shared/ui/Header/Header';
import { Footer } from '@/shared/ui/Footer/Footer';
//types
import { TLocale } from '@/shared/i18n/dictionaries';
//utils
import type { Metadata } from 'next';
import { LocaleInitializer } from '@/shared/i18n/LocaleInitializer';
//fonts
import { roboto } from '@/shared/assets/fonts/roboto';
import { inter } from '@/shared/assets/fonts/inter';
//styles
import 'keen-slider/keen-slider.min.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ru' }];
}

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ lang: TLocale }>;
  children: React.ReactNode;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <LocaleInitializer/>
      <body
        className={`${roboto.variable} ${inter.variable} min-h-screen flex flex-col `}
      >
        <Providers>
          <Header lang={lang}/>
          <main className="grow">
            {children}
          </main>
          <div className="mt-[32px]">
            <Footer lang={lang}/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
