//гш
import Providers from '@/shared/providers';
import { Header } from '@/widgets/Header/Header';
import { Footer } from '@/widgets/Footer/Footer';
//types
import type { Metadata } from 'next';
//fonts
import { roboto } from '@/shared/assets/fonts/roboto';
import { inter } from '@/shared/assets/fonts/inter';
//styles
import 'keen-slider/keen-slider.min.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${inter.variable} min-h-[100vh] flex flex-col `}
      >
        <Providers>
          <Header/>
          <main className="grow">
            {children}
          </main>
          <div className="mt-[32px]">
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
