//components
import Providers from "@/components/providers";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
//types
import type { Metadata } from "next";
//fonts
import { Roboto, Inter } from "next/font/google";
//styles
import "./globals.css";

//TODO: import local fonts

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-roboto'
});

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.variable} ${inter.variable} min-h-[100vh] flex flex-col `}
      >
        <Providers>
          <Header/>
          <main className="grow">
            {children}
          </main>
          <div className="mt-[32px]">
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
